import { Injectable, Logger } from '@nestjs/common';
import sharp from 'sharp';
import { MistralService } from '../mistral/mistral.service.js';

export interface ClassifierVerdict {
  /** 0–100 likelihood the image was AI-generated. */
  score: number;
  /** The model's own confidence, 0–1. */
  confidence: number;
  /** What the model says it saw. */
  observations: string[];
  available: boolean;
  modelUsed: string;
}

const SYSTEM_PROMPT = `You assess whether an image was generated by AI. You are one signal among several, not the decision-maker.

Work through this checklist explicitly before scoring:
1. HANDS AND LIMBS — finger count, joint direction, limbs merging into objects or each other.
2. FACES — asymmetric or mismatched eyes, pupils of different shapes, teeth that merge or multiply, ears that differ in structure, hair that dissolves into the background instead of ending in strands.
3. TEXT — any lettering on signs, packaging, clothing or screens. Generated text is usually malformed, repeated, or approximately-lettered nonsense. This is one of the strongest tells.
4. PHYSICS — shadows falling in inconsistent directions, reflections that do not match their source, light with no plausible source, objects not resting on surfaces.
5. GEOMETRY — walls or furniture that do not line up, railings and tiles whose spacing drifts, background architecture that changes rule mid-span.
6. TEXTURE — skin that is uniformly poreless, fabric whose weave repeats or melts, foliage that dissolves into mush, jewellery and teeth with an unnatural plastic sheen.
7. BACKGROUND COHERENCE — secondary figures with deformed faces or limbs, objects that half-become other objects, crowds that blur into pattern.
8. OVERALL RENDER — the characteristic uniform sharpness, high-contrast micro-detail and slightly waxy lighting of diffusion output, versus real optics with a focal plane and falloff.

Scoring:
- Malformed text, extra or fused fingers, or a background figure with a deformed face are each strong evidence. Score 80+.
- Several softer tells together (waxy skin, uniform focus, drifting geometry) score 60-80.
- A clean, physically coherent image with a real focal plane and natural imperfection scores below 30.
- Photographic imperfection is NOT evidence of generation. Blur, grain, compression, low resolution and awkward framing are normal in real photographs.
- Subject matter is irrelevant. Judge the rendering, not what is depicted.
- If you genuinely cannot tell, score near 50 and set low confidence.

Respond with ONLY this JSON:
{"score": <0-100>, "confidence": <0-1>, "checklistFindings": ["<which numbered check fired and what you saw>", ...], "observations": ["<specific observation>", ...]}`;

/**
 * Image classifier backed by a Mistral vision model.
 *
 * The design doc anticipated a purpose-trained detector API. Mistral's vision
 * model is a general-purpose stand-in: it reasons about visible artefacts
 * rather than detecting generator fingerprints, so it is weighted accordingly
 * and its confidence is carried through to the interval rather than discarded.
 */
@Injectable()
export class ClassifierClientService {
  private readonly logger = new Logger(ClassifierClientService.name);

  /**
   * Generation artefacts live in fine detail — hair, teeth, text, fabric
   * texture, the boundary between objects. Downscaling hard and re-encoding at
   * low quality destroys precisely the evidence the model is being asked to
   * look for, which an earlier version of this file did at 1024px / quality 85.
   */
  private static readonly MAX_EDGE = 1536;
  private static readonly JPEG_QUALITY = 94;

  constructor(private readonly mistral: MistralService) {}

  async classify(buffer: Buffer, context?: string): Promise<ClassifierVerdict> {
    const unavailable: ClassifierVerdict = {
      score: 50,
      confidence: 0,
      observations: [],
      available: false,
      modelUsed: this.mistral.visionModel,
    };

    if (!this.mistral.isConfigured) {
      this.logger.warn('MISTRAL_API_KEY not set — image classifier unavailable.');
      return unavailable;
    }

    let dataUri: string;
    try {
      dataUri = await this.toDataUri(buffer);
    } catch (error) {
      this.logger.error(`Could not prepare image for classification: ${(error as Error).message}`);
      return unavailable;
    }

    const parsed = await this.mistral.completeJson<{
      score?: unknown;
      confidence?: unknown;
      observations?: unknown;
    }>({
      system: SYSTEM_PROMPT,
      user: context
        ? `Assess this image. Context: ${context}`
        : 'Assess this image.',
      model: this.mistral.visionModel,
      images: [dataUri],
      temperature: 0.1,
      maxTokens: 800,
    });

    if (parsed === null) return unavailable;

    const observations = Array.isArray(parsed.observations)
      ? parsed.observations
          .filter((o): o is string => typeof o === 'string' && o.trim().length > 0)
          .slice(0, 8)
      : [];

    return {
      score: clampScore(parsed.score),
      confidence: clamp01(parsed.confidence),
      observations,
      available: true,
      modelUsed: this.mistral.visionModel,
    };
  }

  /** Normalises to a bounded JPEG data URI the vision endpoint accepts. */
  private async toDataUri(buffer: Buffer): Promise<string> {
    const resized = await sharp(buffer)
      .rotate()
      .resize({
        width: ClassifierClientService.MAX_EDGE,
        height: ClassifierClientService.MAX_EDGE,
        fit: 'inside',
        withoutEnlargement: true,
        // Preserves edge detail rather than smoothing it away.
        kernel: 'lanczos3',
      })
      .jpeg({
        quality: ClassifierClientService.JPEG_QUALITY,
        chromaSubsampling: '4:4:4',
      })
      .toBuffer();

    return `data:image/jpeg;base64,${resized.toString('base64')}`;
  }
}

function clampScore(value: unknown): number {
  const n = Number(value);
  if (!Number.isFinite(n)) return 50;
  return Math.max(0, Math.min(100, Math.round(n)));
}

function clamp01(value: unknown): number {
  const n = Number(value);
  if (!Number.isFinite(n)) return 0.5;
  return Math.max(0, Math.min(1, n));
}
